# Generated by Django 4.2.7 on 2023-11-16 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_income', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(500, message='LOW_INCOME')])),
                ('customer_debt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_remarks_12m', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0, message='PAYMENT_REMARKS_12M')])),
                ('payment_remarks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1, message='PAYMENT_REMARKS')])),
                ('customer_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='UNDERAGE')])),
            ],
        ),
    ]
